// @TODO validate envs (zod?) and move them somewhere
export const environment = Object.freeze({
  GOOGLE_SHEETS_API_KEY: process.env.GOOGLE_SHEETS_API_KEY,
  STORYBLOK_ACCESS_TOKEN: process.env.STORYBLOK_ACCESS_TOKEN,
  STORYBLOK_ENVIRONMENT_FOLDER_NAME:
    process.env.STORYBLOK_ENVIRONMENT_FOLDER_NAME,
  STORYBLOK_ESTIMATIONS_FOLDER_ID: process.env.STORYBLOK_ESTIMATIONS_FOLDER_ID,
  STORYBLOK_OAUTH_TOKEN: process.env.STORYBLOK_OAUTH_TOKEN,
  STORYBLOK_SPACE_ID: process.env.STORYBLOK_SPACE_ID,
});
