name: build-staging-store-ios-app
on: workflow_dispatch
jobs:
  build-staging-store-ios-app:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn --immutable
      - name: Build staging store iOS app
        working-directory: ./apps/native
        run: SENTRY_ORG="${{ vars.SENTRY_ORG }}" SENTRY_PROJECT="${{ vars.SENTRY_PROJECT_APP_STAGING }}" SENTRY_AUTH_TOKEN="${{ secrets.SENTRY_AUTH_TOKEN }}" eas build --platform ios --profile staging-store --non-interactive --no-wait
