name: build-production-ios-app
on: workflow_dispatch
jobs:
  build-production-ios-app:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn --immutable
      - name: Build production iOS app
        working-directory: ./apps/native
        run: SENTRY_ORG="${{ vars.SENTRY_ORG }}" SENTRY_PROJECT="${{ vars.SENTRY_PROJECT_PRODUCTION }}" SENTRY_AUTH_TOKEN="${{ secrets.SENTRY_AUTH_TOKEN }}" eas build --platform ios --profile production --non-interactive --no-wait
