name: expo-build
on:
  push:
    branches:
      - "main"
      - "development"
      - "feat/expo-build-in-ci"
jobs:
  expo-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: echo "Hello world"
