name: check-code
on: push
jobs:
  check-code:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn --immutable
      - name: Check typescript
        run: yarn ts:check
      - name: Check eslint
        run: yarn lint
