name: update-production-app
on:
  workflow_dispatch:
    inputs:
      message:
        description: "EAS Update commit message"
        required: true
jobs:
  update-production-app:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn --immutable
      - name: Update production app
        working-directory: ./apps/native
        run: eas update --branch production --message "${{ github.event.inputs.message }}"
